# parameters for imu_odometry_node

# How frequently to publish odometry
publish_hz: 10.0

# Max allowable age of last IMU message, after which
# linear and angular velocities are set to zero
imu_stale_dt: 1.0

# origin reference frame name
origin_frame: "~/odom"

# target reference frame name
target_frame: "~/base_footprint"

# Verbose output
debug: False